addReviewers: true
reviewers:
  - reviewerA
  - reviewerB
  - reviewerC

addSecondaryReviewers: true
secondaryReviewers:
  - reviewerD
  - reviewerE

numberOfReviewers: 1
numberOfSecondaryReviewers: 1

skipKeywords:
  - wip
